import os

MODEL_PROVIDER = os.getenv("MODEL_PROVIDER", "ollama")
MODEL_NAME = os.getenv("MODEL_NAME", os.getenv("OLLAMA_MODEL", "llama3.2"))
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://127.0.0.1:11434")
MODEL_PATH = os.getenv("MODEL_PATH", "")
OFFLOAD_DIR = os.getenv("OFFLOAD_DIR", "./.offload")
MAX_TOKENS = int(os.getenv("MAX_TOKENS", "512"))
CONTEXT_TOKENS = int(os.getenv("CONTEXT_TOKENS", "1024"))
ENABLE_RAG = os.getenv("ENABLE_RAG", "false").lower() == "true"
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "all-MiniLM-L6-v2")
API_HOST = os.getenv("API_HOST", "0.0.0.0")
API_PORT = int(os.getenv("API_PORT", "8000"))
MEMORY_BACKEND = os.getenv("MEMORY_BACKEND", "sqlite")
MEMORY_PATH = os.getenv("MEMORY_PATH", "./data/memory.sqlite3")
MEMORY_TOKEN_BUDGET = int(os.getenv("MEMORY_TOKEN_BUDGET", "768"))
SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY", "")
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY", "")
ZAI_API_KEY = os.getenv("ZAI_API_KEY", os.getenv("ZHIPU_API_KEY", ""))
FALLBACK_PROVIDERS = os.getenv("FALLBACK_PROVIDERS", "groq,gemini,deepseek,zai,ollama")
