/**
 * Core type definitions for the DITroy AI Client SDK.
 */

export interface ChatRequest {
  /** The message prompt to send to the AI. */
  message: string;
  /** Optional conversation ID. Defaults to 'default'. */
  conversation_id?: string;
  /** Alias for conversation_id (camelCase). */
  conversationId?: string;
}

export interface ChatResponse {
  /** The text reply generated by the DITroy AI engine. */
  reply: string;
}

export interface ChatStreamOptions {
  /** Callback fired whenever a new token arrives from the stream. */
  onToken?: (token: string) => void;
  /** Optional AbortSignal to cancel the streaming request early. */
  signal?: AbortSignal;
}

export interface NewConversationRequest {
  /** Optional source conversation ID to inherit learned facts from. Defaults to 'default'. */
  source_conversation_id?: string;
  /** Alias for source_conversation_id (camelCase). */
  sourceConversationId?: string;
}

export interface NewConversationResponse {
  /** The unique ID assigned to the new conversation session. */
  conversation_id: string;
  /** The number of learned facts inherited from the source conversation. */
  inherited_facts: number;
}

export interface ConversationMessage {
  /** Message author role: 'user' | 'assistant' | 'system'. */
  role: string;
  /** Content of the message. */
  content: string;
  /** ISO-8601 creation timestamp. */
  created_at: string;
}

export interface ConversationMessagesResponse {
  conversation_id: string;
  messages: ConversationMessage[];
}

export interface RecentChat {
  conversation_id: string;
  title: string;
  updated_at: string;
}

export interface ConversationListResponse {
  conversations: RecentChat[];
}

export interface HealthStatus {
  status: string;
  service?: string;
  mode?: string;
  provider?: string;
  model?: string;
  model_status?: string;
  available_models?: string[];
  message?: string;
}

export interface DitroyClientOptions {
  /**
   * Base URL of the DITroy AI API backend.
   * @default 'http://localhost:8000' (or process.env.DITROY_API_URL / process.env.NEXT_PUBLIC_API_URL)
   */
  baseUrl?: string;

  /**
   * Request timeout in milliseconds.
   * @default 60000 (60 seconds)
   */
  timeoutMs?: number;

  /**
   * Custom HTTP headers included with all requests.
   */
  headers?: Record<string, string>;

  /**
   * Optional authentication bearer token (e.g. Supabase JWT).
   */
  authToken?: string;

  /**
   * Custom fetch implementation (useful for polyfills, mock environments, or proxying).
   */
  customFetch?: typeof fetch;
}
