#!/usr/bin/env node

const fs = require("fs/promises");
const path = require("path");
const readline = require("readline");

const AUTO_DIR_NAMES = new Set([
  "node_modules",
  ".turbo",
  "dist",
  "build",
  "coverage",
  ".expo",
  ".next",
  ".cache",
  "out",
  "tmp",
  "temp",
]);

const AUTO_FILE_NAMES = new Set([
  ".eslintcache",
  "pnpm-debug.log",
  "npm-debug.log",
  "yarn-error.log",
  "yarn-debug.log",
]);

const AUTO_FILE_SUFFIXES = [".tsbuildinfo", ".tmp", ".temp", ".log", ".cache"];

const colors = {
  reset: "\x1b[0m",
  dim: "\x1b[2m",
  cyan: "\x1b[36m",
  yellow: "\x1b[33m",
  green: "\x1b[32m",
  red: "\x1b[31m",
  magenta: "\x1b[35m",
};

function color(text, tone) {
  return `${colors[tone] ?? ""}${text}${colors.reset}`;
}

function section(title) {
  console.log(`\n${color(`== ${title} ==`, "magenta")}`);
}

function printHelp() {
  console.log(
    `\nPurge Autogenerated Files CLI\n\nUsage:\n  node scripts/purge-files.js [options]\n\nOptions:\n  --dir <path>            Target directory (default: current working directory)\n  --max-depth <n>         Maximum directory traversal depth (default: Infinity)\n  --include <name,name>   Extra names to purge (file or directory names)\n  --exclude <name,name>   Names to protect from purge\n  --no-defaults           Disable built-in autogenerated matching set\n  --dry-run               Show what would be deleted, without deleting\n  --yes                   Skip confirmation prompt\n  --help                  Show this help\n\nDefault autogenerated set includes:\n  node_modules, .turbo, dist, build, coverage, .expo, .next, .cache, out, tmp\n  .eslintcache, *.tsbuildinfo, *.tmp, *.temp, *.log, *.cache\n\nExamples:\n  node scripts/purge-files.js --dry-run\n  node scripts/purge-files.js --dir ./apps/mobile-client --yes\n  node scripts/purge-files.js --include reports --exclude dist --dry-run\n`,
  );
}

function parseArgs(argv) {
  const args = {
    dir: ".",
    useDefaults: true,
  };

  for (let i = 2; i < argv.length; i += 1) {
    const arg = argv[i];
    const next = argv[i + 1];

    if (arg === "--help") {
      args.help = true;
    } else if (arg === "--dry-run") {
      args.dryRun = true;
    } else if (arg === "--yes") {
      args.yes = true;
    } else if (arg === "--no-defaults") {
      args.useDefaults = false;
    } else if (arg === "--dir" && next) {
      args.dir = next;
      i += 1;
    } else if (arg === "--include" && next) {
      args.include = next
        .split(",")
        .map((v) => v.trim())
        .filter(Boolean);
      i += 1;
    } else if (arg === "--exclude" && next) {
      args.exclude = next
        .split(",")
        .map((v) => v.trim())
        .filter(Boolean);
      i += 1;
    } else if (arg === "--max-depth" && next) {
      const value = Number(next);
      if (!Number.isNaN(value) && value >= 0) {
        args.maxDepth = value;
      }
      i += 1;
    }
  }

  return args;
}

function buildSet(baseSet, incoming = []) {
  const next = new Set(baseSet);
  for (const item of incoming) {
    next.add(item.toLowerCase());
  }
  return next;
}

function shouldProtect(name, excludedNames) {
  return excludedNames.has(name.toLowerCase());
}

function matchesAutoFile(name) {
  const lowered = name.toLowerCase();
  if (AUTO_FILE_NAMES.has(lowered)) {
    return true;
  }

  for (const suffix of AUTO_FILE_SUFFIXES) {
    if (lowered.endsWith(suffix)) {
      return true;
    }
  }

  return false;
}

function formatCount(value) {
  return value.toLocaleString("en-US");
}

async function collectPurgeCandidates(rootPath, options) {
  const found = [];

  const dirNames = options.useDefaults
    ? buildSet(AUTO_DIR_NAMES, options.include)
    : buildSet(new Set(), options.include);

  const excludedNames = buildSet(new Set(), options.exclude);

  async function walk(currentPath, depth) {
    let entries;
    try {
      entries = await fs.readdir(currentPath, { withFileTypes: true });
    } catch {
      return;
    }

    for (const entry of entries) {
      const entryName = entry.name;
      const loweredName = entryName.toLowerCase();
      const fullPath = path.join(currentPath, entryName);

      if (shouldProtect(loweredName, excludedNames)) {
        continue;
      }

      if (entry.isDirectory()) {
        if (dirNames.has(loweredName)) {
          found.push({ path: fullPath, type: "dir" });
          continue;
        }

        if (depth < options.maxDepth) {
          await walk(fullPath, depth + 1);
        }
        continue;
      }

      if (!entry.isFile()) {
        continue;
      }

      const isAutoFile = options.useDefaults && matchesAutoFile(entryName);
      const isIncludedFile = dirNames.has(loweredName);

      if (isAutoFile || isIncludedFile) {
        found.push({ path: fullPath, type: "file" });
      }
    }
  }

  await walk(rootPath, 0);
  return found;
}

function printConfig(targetDir, args) {
  section("Configuration");
  console.log(`${color("Root", "cyan")}      : ${targetDir}`);
  console.log(`${color("Dry run", "cyan")}   : ${args.dryRun ? "yes" : "no"}`);
  console.log(
    `${color("Defaults", "cyan")}  : ${args.useDefaults ? "enabled" : "disabled"}`,
  );
  console.log(
    `${color("Max depth", "cyan")}: ${
      Number.isFinite(args.maxDepth) ? String(args.maxDepth) : "Infinity"
    }`,
  );

  if (args.include && args.include.length > 0) {
    console.log(`${color("Include", "cyan")}   : ${args.include.join(", ")}`);
  }
  if (args.exclude && args.exclude.length > 0) {
    console.log(`${color("Exclude", "cyan")}   : ${args.exclude.join(", ")}`);
  }
}

function printMatches(candidates, cwdPath) {
  section("Matches");

  if (candidates.length === 0) {
    console.log(
      color("No autogenerated files or directories matched.", "yellow"),
    );
    return;
  }

  const limit = 200;
  const toPrint = candidates.slice(0, limit);
  const dirCount = candidates.filter((c) => c.type === "dir").length;
  const fileCount = candidates.length - dirCount;

  console.log(
    `${color("Candidates", "cyan")}: ${formatCount(candidates.length)} (${formatCount(dirCount)} directories, ${formatCount(fileCount)} files)`,
  );

  for (const candidate of toPrint) {
    const marker = candidate.type === "dir" ? "DIR " : "FILE";
    console.log(
      `${color(marker, candidate.type === "dir" ? "yellow" : "green")}  ${path.relative(cwdPath, candidate.path)}`,
    );
  }

  if (candidates.length > limit) {
    console.log(
      `${color("...", "dim")} and ${formatCount(candidates.length - limit)} more item(s)`,
    );
  }
}

async function deleteCandidates(candidates) {
  for (const candidate of candidates) {
    if (candidate.type === "dir") {
      await fs.rm(candidate.path, { recursive: true, force: true });
    } else {
      await fs.rm(candidate.path, { force: true });
    }
  }
}

function parseMaxDepth(value) {
  if (typeof value !== "number") {
    return Number.POSITIVE_INFINITY;
  }

  if (!Number.isFinite(value) || value < 0) {
    return Number.POSITIVE_INFINITY;
  }

  return value;
}

function nowMs() {
  return Date.now();
}

function durationLabel(startMs) {
  const elapsedMs = nowMs() - startMs;
  if (elapsedMs < 1000) {
    return `${elapsedMs} ms`;
  }
  return `${(elapsedMs / 1000).toFixed(2)} s`;
}

async function validateDir(targetDir) {
  try {
    const stat = await fs.stat(targetDir);
    return stat.isDirectory();
  } catch {
    return false;
  }
}

function normalizeArgs(args) {
  return {
    ...args,
    maxDepth: parseMaxDepth(args.maxDepth),
    include: args.include ?? [],
    exclude: args.exclude ?? [],
  };
}

function runCommand(cmd, args, opts = {}) {
  const { spawn } = require('child_process');
  return new Promise((resolve, reject) => {
    const p = spawn(cmd, args, { stdio: 'inherit', shell: false, ...opts });
    p.on('close', (code) => {
      if (code === 0) resolve(true);
      else reject(new Error(`${cmd} ${args.join(' ')} exited with code ${code}`));
    });
    p.on('error', (err) => reject(err));
  });
}

async function stopDaemon() {
  section('Stopping daemons');
  const attempts = [
    { cmd: 'npx', args: ['turbo', 'stop'] },
    { cmd: 'pnpm', args: ['dlx', 'turbo', 'stop'] },
    { cmd: 'turbo', args: ['stop'] },
  ];

  for (const a of attempts) {
    try {
      console.log(color(`Trying: ${a.cmd} ${a.args.join(' ')}`, 'dim'));
      // spawn with shell=false; some environments may require shell true, but prefer false for safety
      // allow failures to try next option
      // eslint-disable-next-line no-await-in-loop
      await runCommand(a.cmd, a.args);
      console.log(color('Daemon stop succeeded.', 'green'));
      return true;
    } catch (err) {
      console.log(color(`Attempt failed: ${String(err.message || err)}`, 'yellow'));
      // try next
    }
  }

  console.log(
    color('Could not stop known daemons (turbo). Proceeding with purge, but builds may fail until daemon is stopped.', 'red'),
  );
  return false;
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

function getPidsUsingPath(dir) {
  const { execSync } = require('child_process');
  try {
    // try lsof first
    const out = execSync(`lsof -t +D "${dir}" 2>/dev/null`, { stdio: ['pipe', 'pipe', 'ignore'] }).toString().trim();
    if (out) return Array.from(new Set(out.split(/\s+/).map((s) => Number(s)).filter(Boolean)));
  } catch (e) {
    // ignore
  }

  try {
    // try fuser
    const out = execSync(`fuser -v "${dir}" 2>/dev/null | awk '{print $2}'`, { stdio: ['pipe', 'pipe', 'ignore'] }).toString().trim();
    if (out) return Array.from(new Set(out.split(/\s+/).map((s) => Number(s)).filter(Boolean)));
  } catch (e) {
    // ignore
  }

  try {
    // fallback: pgrep turbo
    const out = execSync(`pgrep -f turbo 2>/dev/null`, { stdio: ['pipe', 'pipe', 'ignore'] }).toString().trim();
    if (out) return Array.from(new Set(out.split(/\s+/).map((s) => Number(s)).filter(Boolean)));
  } catch (e) {
    // ignore
  }

  return [];
}

async function killPids(pids) {
  for (const pid of pids) {
    try {
      process.kill(pid, 'SIGTERM');
    } catch (e) {
      // continue
    }
  }

  await sleep(500);

  for (const pid of pids) {
    try {
      // check if still alive
      process.kill(pid, 0);
      try {
        process.kill(pid, 'SIGKILL');
      } catch (e) {
        // ignore
      }
    } catch (e) {
      // process not running
    }
  }
}

async function ensureRemoved(pathToRemove, tries = 5) {
  for (let i = 0; i < tries; i++) {
    try {
      await fs.rm(pathToRemove, { recursive: true, force: true });
      return true;
    } catch (err) {
      if (err && err.code === 'ENOTEMPTY' || err && err.code === 'EPERM') {
        const pids = getPidsUsingPath(pathToRemove);
        if (pids.length > 0) {
          console.log(color(`Killing processes holding files: ${pids.join(', ')}`, 'yellow'));
          // eslint-disable-next-line no-await-in-loop
          await killPids(pids);
        } else {
          // nothing found, wait and retry
          // eslint-disable-next-line no-await-in-loop
          await sleep(300);
        }
        // retry
        // eslint-disable-next-line no-await-in-loop
        await sleep(200);
        continue;
      }
      throw err;
    }
  }
  return false;
}

function printResult(candidates, wasDryRun, startedAt) {
  section("Result");

  if (wasDryRun) {
    console.log(
      color(
        `Dry run complete. ${formatCount(candidates.length)} item(s) would be removed in ${durationLabel(startedAt)}.`,
        "green",
      ),
    );
    return;
  }

  console.log(
    color(
      `Purge complete. Removed ${formatCount(candidates.length)} item(s) in ${durationLabel(startedAt)}.`,
      "green",
    ),
  );
}

async function run(args) {
  const startedAt = nowMs();
  const cwdPath = process.cwd();
  const targetDir = path.resolve(cwdPath, args.dir);

  const okDir = await validateDir(targetDir);
  if (!okDir) {
    console.error(
      color(`Target directory does not exist: ${targetDir}`, "red"),
    );
    process.exit(1);
  }

  printConfig(targetDir, args);

  const candidates = await collectPurgeCandidates(targetDir, args);
  printMatches(candidates, cwdPath);

  if (candidates.length === 0) {
    section("Result");
    console.log(color("Nothing to purge.", "green"));
    return;
  }

  if (args.dryRun) {
    printResult(candidates, true, startedAt);
    return;
  }

  if (!args.yes) {
    const confirmed = await askForConfirmation(
      `${color("Proceed deleting these autogenerated items?", "yellow")} (y/N): `,
    );
    if (!confirmed) {
      section("Result");
      console.log(color("Aborted by user.", "yellow"));
      return false;
    }
  }

  // Attempt to stop background daemons (turbo) to avoid interference with delete operations
  try {
    // eslint-disable-next-line no-await-in-loop
    await stopDaemon();
  } catch (err) {
    console.log(color('Warning: failed to stop daemon: ' + String(err.message || err), 'yellow'));
  }

  // Attempt to delete candidates with retries and process-kill fallback for locked files
  for (const candidate of candidates) {
    const p = candidate.path;
    try {
      const ok = await ensureRemoved(p);
      if (!ok) {
        console.log(color(`Failed to remove ${p} after retries.`, 'red'));
      }
    } catch (err) {
      console.log(color(`Error removing ${p}: ${String(err.message || err)}`, 'red'));
    }
  }
  printResult(candidates, false, startedAt);
}

function askForConfirmation(message) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    rl.question(message, (answer) => {
      rl.close();
      resolve(answer.trim().toLowerCase() === "y");
    });
  });
}

async function main() {
  const parsed = parseArgs(process.argv);

  if (parsed.help) {
    printHelp();
    process.exit(0);
  }

  const args = normalizeArgs(parsed);
  await run(args);
}

main().catch((error) => {
  console.error(
    color(error instanceof Error ? error.message : String(error), "red"),
  );
  process.exit(1);
});
